apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: niifcd1ts-nodejs
  janus-idp.io/tekton: niifcd1ts-nodejs
  backstage.io/kubernetes-id: niifcd1ts-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: niifcd1ts-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
