apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: niifcd1ts-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: niifcd1ts-nodejs 
  name: niifcd1ts-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: niifcd1ts-nodejs 
